# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Silhouette VTLee"
license = "MIT"
licenselink = "https://github.com/VTLee/silhouette-vtlee/blob/master/LICENSE"
description = "A responsive blog theme for Hugo."
homepage = "https://ldoughty.com/"
tags = ["blog, responsive, personal, bootstrap, disqus, google analytics, syntax highligting, font awesome, landing page, flexbox"]
features = ["blog", "bootstrap","responsive"]
min_version = "0.51"

[author]
name = "Lee Doughty"
homepage = "https://ldoughty.com/"
